### PR TITLE
Change `eza_params`

### PR DESCRIPTION
**Pull request by xaocon**
* Added `all` to `color-scale` to fix breaking change
* Removed `classify` as there is a bug when combined with `icons` https://github.com/eza-community/eza/issues/578

### CODE REVIEW

**Comment by xaocon** [comment]
I don't think I can add labels. If you want to fix the breaking change another way feel free to just close this and put your own in. Just wanted to get a fix in as fast as possible since this breaks `ls` on my machine and presumably a number of other ones once they install the new version of eza.

**Comment by cafkafk** [comment]
Sorry, I wasn't aware that we introduced a breaking change? Normally we do label them correctly.

**Comment by meinzer1899** [comment]
@cafkafk maybe these infos help
grafik

**Comment by cafkafk** [comment]
I see how I made this mistake, I assumed the breaking change in the relevant PR was just referring to changing `--decay` to `--color-scale` (`--decay` having never been released), and thought there was no reason to label it a breaking change. In reality, the breaking change was partially that, but also requiring an argument. If I had realized that sooner, I'd have required `--color-scale` to default to `all`, and until eza has that behavior, I'll consider that a bug. Sorry for the inconvenience!

**Comment by xaocon** [comment]
@cafkafk, glad you're already considering stuff like that.

**Comment by xfoxfu** [comment]
For anyone who needs a workaround and is on zi/zinit, please use:

```zsh
zi ice has'eza' atinit'AUTOCD=0' atload'eza_params[3]="";eza_params[7]="--color-scale=all"'
zi light z-shell/zsh-eza
```

**Review by ss-o — APPROVED** [review]

**Comment by ss-o** [comment]
@xaocon :wave: , thank you for your contribution!

**Pull request merged**
